services:
  db:
    image: mariadb:lts-ubi9
    container_name: mariadb  # Easier to remember
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb # Saves your data!

volumes:
  mariadb_data: # Declares the volume
